config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'resources#index'
  get 'service', to: 'resources#show'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController

  def index
    @api = Specification.instance.api
  end

  def show
    @base_url = Specification.instance.api[:base_url]
    @service = Specification.instance.service params[:method], params[:resource]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/specification.rb
class Specification

  include Singleton

  def api
    return @api unless @api.nil?
    api_specification_file = Rails.configuration.api_specification_file
    return nil unless File.exist?(api_specification_file)
    specification = YAML.load_file(api_specification_file)
    @api ||= {
      title: "#{specification['info']['title']} - versão #{specification['info']['version']}",
      description: "#{specification['info']['description']}",
      base_url: "#{specification['schemes'][0]}://#{specification['host']}#{specification['basePath']}",
      services: services(specification['paths'])
    }
  end

  def service(method, resource)
    @api[:services].find{|service| service[:method] == method && service[:resource] == resource}
  end

  private

  def services(paths)
    retorno = []
    paths.each do |resource, resource_value|
      resource_value.each do |method, method_value|
        retorno << {
          method: method,
          resource: resource,
          description: method_value['description'],
          parameters: parameters(method_value['parameters'])
        }
      end
    end
    retorno
  end

  def parameters(parameters)
    retorno = []
    parameters.each do |parameter|
      retorno << {
        name: parameter['name'],
        description: parameter['description'],
        required: parameter['required'],
        type: parameter['type']
      }
    end
    retorno
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Frontend</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/resources/_service.html.erb
<% service_url = base_url + service[:resource] %>
<%= link_to "#{service[:method]} #{service[:resource]}(#{service[:parameters].map{|p| p[:name]}.join(', ')})", service_path(method: service[:method], resource: service[:resource]) %> - <%= "#{service[:description]}" %>
</br>

app/views/resources/index.html.erb
<%= @api[:title] %></br>
<%= @api[:description] %></br>
<%= @api[:base_url] %></br>
</br>
<%= render partial: 'service', collection: @api[:services], as: :service, locals: {base_url: @api[:base_url]} %>

app/views/resources/show.html.erb
<%= form_tag @base_url + @service[:resource], method: @service[:method] do %>
  <% @service[:parameters].each do |parameter| %>
    <%= label_tag parameter[:name] %><%= text_field_tag parameter[:name], nil, placeholder: parameter[:description] %></br>
  <% end %>
  <%= submit_tag "Excuta" %>
<% end %>